name = "v2ray"
main = "src/index.mjs"
compatibility_date = "2026-01-09"
minify = true
workers_dev = true

routes = [
  { pattern = "bgtok.qzz.io", custom_domain = true }
]

[[kv_namespaces]]
binding = "SIREN"
id = "7ce9263ec11c4bd199e5fee9b7d9e862"

[vars]
UUID = "85dba49f-78a8-4050-a8f0-2185134fa358"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/crone-hackx/V2ray/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/crone-hackx/V2ray/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/crone-hackx/V2ray/refs/heads/master/web/link.html"
