name = "gardevoir"
main = "build/worker/shim.mjs"
compatibility_date = "2026-01-09"
minify = true
workers_dev = true

routes = [
  { pattern = "gardevoir.bluehat358.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.gardevoir.bluehat358.biz.id", custom_domain = true },
  { pattern = "df.game.naver.com.gardevoir.bluehat358.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.gardevoir.bluehat358.biz.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.gardevoir.bluehat358.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.gardevoir.bluehat358.biz.id", custom_domain = true },  
  { pattern = "cache.netflix.com.gardevoir.bluehat358.biz.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.gardevoir.bluehat358.biz.id", custom_domain = true },
  { pattern = "img.email1.vidio.com.gardevoir.bluehat358.biz.id", custom_domain = true }
]

[[kv_namespaces]]
binding = "SIREN"
id = "7ce9263ec11c4bd199e5fee9b7d9e862"

[vars]
UUID = "85dba49f-78a8-4050-a8f0-2185134fa358"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/crone-hackx/V2ray/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/crone-hackx/V2ray/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/crone-hackx/V2ray/refs/heads/master/web/link.html"
